### ISSUE TITLE
[Data] Could you provide a list including the files of something-something v2 which should be downloaded?

### ISSUE THREAD

**Issue by aopolin-lv** [AILab-CVC/SEED-Bench#6]
Hi, in the something-something v2 (SSv2) website, it contains 20 packages like `20BN-Something-Something Download Package xx` for downloading. You mentioned the evaluation dont use all the videos. So could you provide a list include the used download packages formulated like mentioned above?

**Comment by Bohao-Lee** [comment]
Thank you very much for your interest in our work. Regarding the ssv2 data set, we recommend downloading all packages, because it may affect the decompression of files. ssv2 dataset download instructions: In order to extract the TGZ archive, the 20 files must be downloaded and concatenated in the right order. Only then they can be extracted.

**Comment by aopolin-lv** [comment]
Thank you for your response!

**Comment by Aopolin-Lv** [comment]
By the way, could you provide the source code for testing model `blip2_vicuna_instruct`?
I do following steps and dont know whether it is consistency with yours:
step1: I concatenate each choice behind its question to form 4 input sentences as the input
step2: forward the sentences and compute their loss
step3: pick the choice with the minimum loss as the final result
